site_name: Audio Streaming Reaserch Group 
site_url: https://github.com/ddgg-el/audio-streaming-group
repo_name: audio-streaming-group
repo_url: https://github.com/ddgg-el/audio-streaming-group

nav:
  - Home: index.md
  - Introduzione: introduzione.md
  - Software Esistenti: softwares.md 


plugins:
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: Archive
      archive_toc: false
      categories: true
      categories_name: Categories
      categories_slugify_separator: "-"
      categories_toc: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: false
  - rss:
  #     abstract_chars_count: 160
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date
      enabled: true
  #     feed_ttl: 1440
  #     image: "null"
  #     json_feed_enabled: true
  #     length: 20
      match_path: blog/posts/.*
  #     pretty_print: false
  #     rss_feed_enabled: true
  #     use_git: false
  #     use_material_social_cards: true


theme:
  name: material
  language: it
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - announce.dismiss
extra:
  generator: false

  
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
extra_css:
  - stylesheets/extra.css